### PR TITLE
Add example for host, port and db options [ckip ci]

### PR DESCRIPTION
**Pull request by artofhuman**

### CODE REVIEW

**Comment by sorentwo** [comment]
Updating this is a great idea!

It passes the config directly to redis, so any options that it accepts would work well. I think it is better to link to redis config documentation and note that anything can be passed through.

**Comment by artofhuman** [comment]
@sorentwo i update readme and add link to redis gem. WDYT?

**Comment by sorentwo** [comment]
Looks good! I'm going to pull it down and merge manually, just to tweak the language a little.

**Comment by artofhuman** [comment]
Thanks!

**Pull request merged**
